# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
- job: linux_js
  variables:
  - template: ci/azure/variables-docker.yaml
  condition: 'false'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: 'ci/azure/linux-js.yaml'

- job: linux_cpp_debug
  variables:
  - template: ci/azure/variables-docker.yaml
  condition: 'true'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: 'ci/azure/linux-cpp.yaml'
    parameters:
      buildType: Debug

- job: linux_cpp_release
  variables:
  - template: ci/azure/variables-docker.yaml
  condition: 'false'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: 'ci/azure/linux-cpp.yaml'
    parameters:
      buildType: Release

- job: windows_cpp_debug
  condition: 'false'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: 'ci/azure/windows-cpp.yaml'
    parameters:
      buildType: Debug

- job: windows_cpp_release
  condition: 'false'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: 'ci/azure/windows-cpp.yaml'
    parameters:
      buildType: Release

- job: macos_cpp_debug
  condition: 'false'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: 'ci/azure/macos-cpp.yaml'
    parameters:
      buildType: Debug

- job: macos_cpp_release
  condition: 'false'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: 'ci/azure/macos-cpp.yaml'
    parameters:
      buildType: Release
